# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [3]:
import numpy as np


#### Create an array of 10 zeros 

In [ ]:
arr=np.array([0,0,0,0,0,0,0,0,0])
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [ ]:
arr=np.full([1,10],1)
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### Create an array of 10 fives

In [ ]:
arr=np.full([1,10],5)
arr

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

#### Create an array of the integers from 10 to 50

In [ ]:
arr=np.full([1,41],range(10,51))
arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

#### Create an array of all the even integers from 10 to 50

In [ ]:
arr=np.full([1,41],range(10,51))
arr[arr%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
arr=np.full([1,9],range(0,9))
arr.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
arr=np.array([1,0,0,0,1,0,0,0,1])
arr.reshape(3,3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
arr=np.array([np.random.uniform(0,1)])
arr

array([0.98424474])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
arr=np.array([np.random.uniform(-2,2,size=(5,5))])
# arr.reshape(5,5)
arr

array([[[-0.73181543, -1.0535342 ,  0.99845229, -1.20811221,
         -1.80150842],
        [-0.81408882,  1.03589328,  0.74933585, -0.59918919,
          1.32592608],
        [ 0.07789072,  0.65320821, -1.0234568 ,  0.19576903,
         -0.95311554],
        [ 1.59535036, -1.3214623 ,  0.18959795, -1.60584594,
          0.19871335],
        [-0.13732862, -1.44601871, -0.88639893,  1.27581482,
         -0.50787925]]])

#### Create the following matrix:

In [5]:
arr=np.array([ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ,
        0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ,
        0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ,
        0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ,
        0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ,
        0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,
        0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,
        0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,
        0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ,
0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1])
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [10]:
arr=np.array([np.random.uniform(0,1,size=(1,20))])
arr.sort()
arr

array([[[0.01033955, 0.0742036 , 0.09351982, 0.10337429, 0.1572073 ,
         0.27334213, 0.27415035, 0.34834728, 0.45475456, 0.53900955,
         0.54001697, 0.55679113, 0.5716941 , 0.75212711, 0.7634393 ,
         0.84886142, 0.88494865, 0.89683901, 0.92076369, 0.95882331]]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat = np.arange(12,26)
np.delete(mat,(4,9)).reshape(3,4)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3][4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[0:3,1]

array([ 2,  7, 12])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[4][0:4]

array([21, 22, 23, 24])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [ ]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!